FROM rust:1.66 as builder
# Use prebuilt builder image
# FROM rust:1.50-prebuilt as builder
RUN apt-get update
RUN apt-get install apt-utils -y
RUN apt-get install software-properties-common -y
RUN apt-get update
RUN apt-get install -y libjemalloc-dev zsh

# oh my zsh
# Default powerline10k theme, no plugins installed
RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.5/zsh-in-docker.sh)" -- \
    -t robbyrussell \
    -p git
RUN chsh -s $(which zsh)

# nvm and node
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
RUN . ~/.nvm/nvm.sh && nvm install 18